apiVersion: apps/v1
kind: Deployment
metadata:
    name: p2
spec:
    replicas: 3
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 100%
    selector:
        matchLabels:
            app: p2
    template:
        metadata:
            labels:
                app: p2
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        - labelSelector:
                              matchExpressions:
                                  [{ key: app, operator: In, values: [p2] }]
                          topologyKey: 'kubernetes.io/hostname'
            containers:
                - name: go-hello
                  image: tinahmgao/go-hello
                  ports:
                      - name: http
                        containerPort: 8080
            terminationGracePeriodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
    name: p2svc
spec:
    type: NodePort
    selector:
        app: p2
    ports:
        - name: p2port
          protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30200
